-- Create a table for public profiles (optional, but good practice)
create table public.profiles (
  id uuid references auth.users not null primary key,
  email text,
  role text default 'citizen',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Create a table for issues
create table public.issues (
  id bigint generated by default as identity primary key,
  user_id uuid references auth.users, -- Optional link to user if logged in
  type text not null,
  description text,
  lat double precision,
  lng double precision,
  location text,
  image_url text,
  status text default 'PENDING', -- PENDING, RESOLVED, APPROVED, REJECTED
  resolved_image_url text,
  priority text default 'Moderate',
  risk text default 'Moderate',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()) not null
);

-- Enable Row Level Security
alter table public.profiles enable row level security;
alter table public.issues enable row level security;

-- Policies for Profiles
create policy "Public profiles are viewable by everyone." on public.profiles
  for select using (true);

create policy "Users can insert their own profile." on public.profiles
  for insert with check (auth.uid() = id);

create policy "Users can update own profile." on public.profiles
  for update using (auth.uid() = id);

-- Policies for Issues
-- Everyone can view issues (or maybe just citizens/admins?) -> Let's say everyone for transparency
create policy "Issues are viewable by everyone." on public.issues
  for select using (true);

-- Authenticated users can create issues (or anon if we allow anon reports)
-- Let's allow anon for now to match previous local flow, or restrict to auth. 
-- The local flow allowed anon. Supabase anon key allows connection, but RLS might block.
-- If we want strict auth:
create policy "Authenticated users can insert issues." on public.issues
  for insert with check (auth.role() = 'authenticated');
  
-- If we want anon reports, we'd need to allow anon role, but let's stick to auth for better tracking

-- Only Admins/Govt Workers should update status
-- For simplicity in this demo, we'll check a 'role' in metadata or profile, 
-- REMINDER: Verify your custom claims or profile role logic. 
-- For now, let's allow any authenticated user to UPDATE for the sake of the demo (since we settle roles in frontend).
-- IN PRODUCTION: Use a strict policy based on app_metadata or lookups.
create policy "Authenticated users can update issues." on public.issues
  for update using (auth.role() = 'authenticated');

-- Storage Bucket for Images
insert into storage.buckets (id, name, public) values ('issues', 'issues', true);

-- Storage Policies
create policy "Images are publicly accessible." on storage.objects
  for select using (bucket_id = 'issues');

create policy "Authenticated users can upload images." on storage.objects
  for insert with check (bucket_id = 'issues' and auth.role() = 'authenticated');
